#!/usr/bin/env python3
"""Copy FastClinic's synthetic clinical SQLite model into PostgreSQL.

The migration is transactionally isolated to one schema (``fast_clinic`` by
default). It never logs the database URL and refuses to replace existing
FastClinic tables unless ``--replace`` is explicitly supplied.
"""
from __future__ import annotations

import argparse
import os
import re
import sqlite3
from pathlib import Path

from dotenv import load_dotenv
import psycopg2
from psycopg2 import sql
from psycopg2.extras import execute_values


ROOT = Path(__file__).resolve().parents[1]
TABLES = (
    "subject",
    "diagnosis",
    "note",
    "item",
    "consultation",
    "party",
    "subject_party_role",
)
SCHEMA_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        type=Path,
        default=ROOT / "fastclinic.sqlite",
        help="source SQLite database (default: fastclinic.sqlite)",
    )
    parser.add_argument(
        "--url-env",
        default="DATABASE_URL_PROD",
        help="environment variable containing the PostgreSQL URL",
    )
    parser.add_argument(
        "--schema",
        default=os.getenv("FASTCLINIC_DB_SCHEMA") or "fast_clinic",
        help="isolated target schema (default: fast_clinic)",
    )
    parser.add_argument(
        "--replace",
        action="store_true",
        help="replace the seven known FastClinic tables if they already exist",
    )
    return parser.parse_args()


def sqlite_columns(source: sqlite3.Connection, table: str) -> list[sqlite3.Row]:
    rows = source.execute(f'PRAGMA table_info("{table}")').fetchall()
    if not rows:
        raise RuntimeError(f"source table {table!r} is missing")
    return rows


def pg_type(sqlite_type: str) -> sql.SQL:
    normalized = (sqlite_type or "TEXT").upper()
    if "INT" in normalized:
        return sql.SQL("BIGINT")
    if any(token in normalized for token in ("REAL", "FLOA", "DOUB", "NUM", "DEC")):
        # NUMERIC preserves cent-level totals and supports PostgreSQL's
        # ROUND(value, precision) form used throughout the dashboards.
        return sql.SQL("NUMERIC")
    if "BLOB" in normalized:
        return sql.SQL("BYTEA")
    return sql.SQL("TEXT")


def create_table_statement(table: str, columns: list[sqlite3.Row]) -> sql.Composed:
    primary = [column["name"] for column in columns if column["pk"]]
    definitions: list[sql.Composable] = []
    for column in columns:
        name = column["name"]
        single_identity = len(primary) == 1 and primary[0] == name and "INT" in column["type"].upper()
        parts: list[sql.Composable] = [sql.Identifier(name)]
        if single_identity:
            parts.append(sql.SQL("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"))
        else:
            parts.append(pg_type(column["type"]))
            if column["notnull"]:
                parts.append(sql.SQL("NOT NULL"))
            if column["dflt_value"] is not None:
                parts.extend((sql.SQL("DEFAULT"), sql.SQL(str(column["dflt_value"]))))
        definitions.append(sql.SQL(" ").join(parts))
    if len(primary) > 1:
        definitions.append(
            sql.SQL("PRIMARY KEY ({})").format(
                sql.SQL(", ").join(map(sql.Identifier, primary))
            )
        )
    return sql.SQL("CREATE TABLE {} ({})").format(
        sql.Identifier(table), sql.SQL(", ").join(definitions)
    )


def existing_tables(cursor) -> set[str]:
    cursor.execute(
        """SELECT table_name FROM information_schema.tables
           WHERE table_schema=current_schema() AND table_name=ANY(%s)""",
        (list(TABLES),),
    )
    return {row[0] for row in cursor.fetchall()}


def copy_table(source: sqlite3.Connection, cursor, table: str) -> int:
    columns = sqlite_columns(source, table)
    names = [column["name"] for column in columns]
    rows = source.execute(f'SELECT * FROM "{table}"').fetchall()
    if rows:
        statement = sql.SQL("INSERT INTO {} ({}) VALUES %s").format(
            sql.Identifier(table), sql.SQL(", ").join(map(sql.Identifier, names))
        )
        execute_values(cursor, statement.as_string(cursor), [tuple(row) for row in rows], page_size=1000)
    primary = [column["name"] for column in columns if column["pk"]]
    if len(primary) == 1 and "INT" in columns[names.index(primary[0])]["type"].upper():
        cursor.execute(
            "SELECT pg_get_serial_sequence(%s, %s)", (table, primary[0])
        )
        sequence = cursor.fetchone()[0]
        if sequence:
            cursor.execute(
                sql.SQL("SELECT MAX({}) FROM {}").format(
                    sql.Identifier(primary[0]), sql.Identifier(table)
                )
            )
            maximum = cursor.fetchone()[0]
            cursor.execute("SELECT setval(%s, %s, %s)", (sequence, maximum or 1, maximum is not None))
    return len(rows)


def verify(source: sqlite3.Connection, cursor) -> dict[str, int]:
    counts: dict[str, int] = {}
    for table in TABLES:
        expected = source.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0]
        cursor.execute(sql.SQL("SELECT COUNT(*) FROM {}").format(sql.Identifier(table)))
        actual = cursor.fetchone()[0]
        if actual != expected:
            raise RuntimeError(f"verification failed for {table}: expected {expected}, got {actual}")
        counts[table] = actual

    checks = {
        "orphan_consultations": """SELECT COUNT(*) FROM consultation c
            LEFT JOIN subject s ON s.id=c.subject_id
            WHERE c.subject_id IS NOT NULL AND s.id IS NULL""",
        "orphan_roles": """SELECT COUNT(*) FROM subject_party_role r
            LEFT JOIN subject s ON s.id=r.subject_id
            LEFT JOIN party p ON p.id=r.party_id
            WHERE s.id IS NULL OR p.id IS NULL""",
    }
    for label, statement in checks.items():
        cursor.execute(statement)
        if cursor.fetchone()[0]:
            raise RuntimeError(f"verification failed: {label}")

    expected_revenue = source.execute(
        "SELECT ROUND(COALESCE(SUM(line_total_vat),0),2) FROM item"
    ).fetchone()[0]
    cursor.execute("SELECT ROUND(COALESCE(SUM(line_total_vat),0)::numeric,2) FROM item")
    actual_revenue = float(cursor.fetchone()[0])
    if abs(float(expected_revenue) - actual_revenue) > 0.01:
        raise RuntimeError("verification failed: item revenue checksum differs")
    return counts


def migrate(source_path: Path, database_url: str, schema: str, replace: bool) -> dict[str, int]:
    if not SCHEMA_RE.fullmatch(schema):
        raise RuntimeError("schema is not a valid SQL identifier")
    if not source_path.is_file():
        raise RuntimeError(f"source database does not exist: {source_path}")

    source = sqlite3.connect(f"file:{source_path}?mode=ro", uri=True)
    source.row_factory = sqlite3.Row
    target = psycopg2.connect(database_url, connect_timeout=10)
    try:
        with target:
            with target.cursor() as cursor:
                cursor.execute(
                    sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(sql.Identifier(schema))
                )
                cursor.execute(
                    sql.SQL("SET LOCAL search_path TO {}").format(sql.Identifier(schema))
                )
                present = existing_tables(cursor)
                if present and not replace:
                    names = ", ".join(sorted(present))
                    raise RuntimeError(
                        f"target schema already contains FastClinic tables ({names}); "
                        "re-run with --replace only after confirming replacement is safe"
                    )
                for table in reversed(TABLES):
                    cursor.execute(
                        sql.SQL("DROP TABLE IF EXISTS {} CASCADE").format(sql.Identifier(table))
                    )
                for table in TABLES:
                    cursor.execute(create_table_statement(table, sqlite_columns(source, table)))
                    copy_table(source, cursor, table)
                cursor.execute("CREATE INDEX idx_spr_subject ON subject_party_role (subject_id)")
                cursor.execute("CREATE INDEX idx_spr_party ON subject_party_role (party_id)")
                return verify(source, cursor)
    finally:
        source.close()
        target.close()


def main() -> None:
    args = arguments()
    load_dotenv(ROOT / ".env")
    database_url = os.getenv(args.url_env)
    if not database_url:
        raise SystemExit(f"{args.url_env} is missing or empty")
    try:
        counts = migrate(args.source.resolve(), database_url, args.schema, args.replace)
    except Exception as exc:
        raise SystemExit(f"Migration aborted: {exc}") from exc
    print(f"Migrated and verified synthetic clinical data in schema {args.schema}:")
    for table, count in counts.items():
        print(f"  {table:20} {count:>8}")


if __name__ == "__main__":
    main()
